// AI tracker test
// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';
import { CopilotTracker } from './tracker';
import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';
import * as os from 'os';

// Create a global output channel
export const logger = vscode.window.createOutputChannel("AI Tracker Debug");

// Minimal Git API definition
interface GitAPI {
    repositories: Repository[];
}
interface Repository {
    rootUri: vscode.Uri;
}
interface GitExtension {
    getAPI(version: number): GitAPI;
}

export function activate(context: vscode.ExtensionContext) {
    logger.appendLine('ACTIVATE: Extension is starting...');
	console.log('ACTIVATE: Extension is starting (console)...');
    
    // Setup global git hooks
    setupGlobalGitHooks(context);
    
    // Setup Copilot agent hooks
    setupCopilotHooks(context);

    // Remove stale per-repo hook configs left by older extension versions
    cleanupLegacyRepoHooks();

    // Ensure Co-authored-by trailer is added for AI contributions
    ensureAICoAuthorSetting();

    // Ensure OTEL DB span exporter is enabled so token usage is captured locally
    ensureOtelDbSpanExporter();
    
    let tracker: CopilotTracker | undefined;

    try {
        tracker = new CopilotTracker(logger);
        context.subscriptions.push(tracker);
        logger.appendLine('ACTIVATE: Tracker initialized.');
    } catch (e) {
        logger.appendLine(`ERROR: Failed to init tracker: ${e}`);
        console.error(e);
    }

	const disposable = vscode.commands.registerCommand('copilot-insight-tracker.helloWorld', () => {
		vscode.window.showInformationMessage('Copilot Insight Tracker is running.');
        logger.appendLine('COMMAND: Hello World triggered');
    });

	context.subscriptions.push(disposable);
    
    return { tracker };
}

/**
 * Setup global git hooks that work across all repositories
 */
function setupGlobalGitHooks(context: vscode.ExtensionContext): void {
    try {
        // Create a global hooks directory in the extension's global storage
        const globalHooksDir = path.join(context.globalStorageUri.fsPath, 'git-hooks');
        
        if (!fs.existsSync(globalHooksDir)) {
            fs.mkdirSync(globalHooksDir, { recursive: true });
            logger.appendLine(`[Setup] Created global hooks directory: ${globalHooksDir}`);
        }

        const hookFile = path.join(globalHooksDir, 'commit-msg');

        // Embed the hook-handler path using forward slashes so Git's POSIX sh
        // can reference it on all platforms (Node.js accepts forward slashes on Windows)
        const hookHandlerPath = path.join(context.globalStorageUri.fsPath, 'copilot-hooks', 'hook-handler.js')
            .replace(/\\/g, '/');

        // The commit-msg hook sources nvm/profile files at runtime so node is found
        // even in Git's restricted hook environment (no baked-in path needed).


        // Create/update the commit-msg hook
        const hookContent = `#!/bin/sh
# Auto-generated by AI Contribution Tracker Extension
# This hook runs globally for all repositories

HOOK_HANDLER="${hookHandlerPath}"
IMPACT_FLAG=$(git rev-parse --git-path AI_IMPACT_PENDING)
STATE_FILE=$(git rev-parse --git-path ai-tracker-state.json)

# Source common profile files so node is found even in restricted Git hook envs
export NVM_DIR="\${NVM_DIR:-$HOME/.nvm}"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" --no-use
[ -f "$HOME/.asdf/asdf.sh" ] && . "$HOME/.asdf/asdf.sh"
[ -d "$HOME/.volta/bin" ] && export PATH="$HOME/.volta/bin:$PATH"
for _brew_bin in /opt/homebrew/bin /usr/local/bin; do
  [ -x "$_brew_bin/node" ] && export PATH="$_brew_bin:$PATH" && break
done

NODE_BIN=""
for _candidate in \
    "$HOME/.volta/bin/node" \
    "$HOME/.asdf/shims/node" \
    /opt/homebrew/bin/node \
    /usr/local/bin/node \
    /usr/bin/node; do
    if [ -x "$_candidate" ]; then
        NODE_BIN="$_candidate"
        break
    fi
done

if [ -z "$NODE_BIN" ] && [ -d "$NVM_DIR/versions/node" ]; then
    NODE_BIN=$(find "$NVM_DIR/versions/node" -path '*/bin/node' -type f 2>/dev/null | sort -r | head -n 1)
fi

if [ -z "$NODE_BIN" ]; then
    NODE_BIN=$(command -v node 2>/dev/null || true)
fi

if [ -z "$NODE_BIN" ]; then
    echo "AI Commit Tracker: node not found in commit-msg hook environment" >&2
    exit 127
fi

# If a session is in progress, refresh the flag with live OTEL token data.
# This ensures token counts appear even when the commit happens before Stop fires.
if [ -f "$STATE_FILE" ] && [ -f "$HOOK_HANDLER" ]; then
    GIT_ABS_DIR=$(git rev-parse --absolute-git-dir)
    printf '{"hookEventName":"CommitMsg","cwd":".","gitDir":"%s"}' "$GIT_ABS_DIR" | "$NODE_BIN" "$HOOK_HANDLER" > /dev/null 2>&1 || true
fi

if [ -f "$IMPACT_FLAG" ]; then
    MARKER=$(cat "$IMPACT_FLAG")
    if [ -z "$MARKER" ]; then
        MARKER="Impacted by AI"
    fi
    if ! grep -qF "$MARKER" "$1"; then
        echo "" >> "$1"
        echo "$MARKER" >> "$1"
    fi
    rm "$IMPACT_FLAG"
fi

# Clean up accumulated hook state after commit
if [ -f "$STATE_FILE" ]; then
    rm "$STATE_FILE"
fi
`.replace(/\r\n/g, '\n');

        fs.writeFileSync(hookFile, hookContent);
        
        // Make executable on Unix-like systems
        if (os.platform() !== 'win32') {
            fs.chmodSync(hookFile, '755');
        }
        
        logger.appendLine(`[Setup] Created/updated commit-msg hook: ${hookFile}`);

        // Check current git global config
        let currentHooksPath: string = '';
        try {
            currentHooksPath = execSync('git config --global core.hooksPath', { 
                encoding: 'utf8',
                stdio: ['pipe', 'pipe', 'pipe']
            }).trim();
        } catch {
            // Not set, which is fine
        }

        // Set global hooks path if not already set to our directory
        if (currentHooksPath !== globalHooksDir) {
            if (currentHooksPath) {
                logger.appendLine(`[Setup] Existing global hooks path: ${currentHooksPath}`);
                logger.appendLine(`[Setup] Will update to extension hooks path: ${globalHooksDir}`);
            }
            
            execSync(`git config --global core.hooksPath "${globalHooksDir}"`, { 
                encoding: 'utf8',
                stdio: ['pipe', 'pipe', 'pipe']
            });
            
            logger.appendLine(`[Setup] ✓ Set global git hooks path: ${globalHooksDir}`);
            logger.appendLine(`[Setup] All repositories will now use AI tracking hooks automatically`);
            
            // Show notification to user
            vscode.window.showInformationMessage(
                'AI Contribution Tracker: Global git hooks configured successfully. All repositories will now track AI contributions.',
                'Show Logs'
            ).then(selection => {
                if (selection === 'Show Logs') {
                    logger.show();
                }
            });
        } else {
            logger.appendLine(`[Setup] Global hooks path already configured: ${globalHooksDir}`);
        }

    } catch (error) {
        logger.appendLine(`[Setup] ERROR setting up global hooks: ${error}`);
        vscode.window.showWarningMessage(
            `AI Contribution Tracker: Failed to setup global git hooks. Manual installation may be required.`,
            'Show Logs'
        ).then(selection => {
            if (selection === 'Show Logs') {
                logger.show();
            }
        });
    }
}

/**
 * Setup Copilot agent hooks globally (~/.copilot/hooks/)
 * These hooks fire during agent sessions to track prompts, agents, and models.
 */
function setupCopilotHooks(context: vscode.ExtensionContext): void {
    try {
        // Copy hook-handler.js to a stable location in global storage
        const hookHandlerDir = path.join(context.globalStorageUri.fsPath, 'copilot-hooks');
        if (!fs.existsSync(hookHandlerDir)) {
            fs.mkdirSync(hookHandlerDir, { recursive: true });
        }

        const bundledHandler = path.join(context.extensionPath, 'dist', 'hook-handler.js');
        const installedHandler = path.join(hookHandlerDir, 'hook-handler.js');

        if (fs.existsSync(bundledHandler)) {
            fs.copyFileSync(bundledHandler, installedHandler);
            logger.appendLine(`[Setup] Copied hook-handler.js to: ${installedHandler}`);
        } else {
            logger.appendLine(`[Setup] WARNING: hook-handler.js not found at: ${bundledHandler}`);
            return;
        }

        // Create hook config pointing to the installed handler
        const userHome = os.homedir();
        const copilotHooksDir = path.join(userHome, '.copilot', 'hooks');
        if (!fs.existsSync(copilotHooksDir)) {
            fs.mkdirSync(copilotHooksDir, { recursive: true });
        }

        // Build the command string.
        // On Mac/Linux the Copilot hooks subprocess inherits VS Code's restricted
        // environment (not the user's shell), so nvm / Homebrew node may be missing.
        // We create a thin wrapper shell script that sources common profile files
        // before finding and invoking node, rather than baking a path that might
        // be wrong or change after an nvm version switch.
        const handlerPathPosix = installedHandler.replace(/\\/g, '/');
        let defaultCommand: string;
        let windowsCommand: string;

        if (os.platform() !== 'win32') {
            // Create a wrapper script in the same hooks dir
            const wrapperPath = path.join(hookHandlerDir, 'run-hook.sh');
            const wrapperPathPosix = wrapperPath.replace(/\\/g, '/');
            const wrapperContent = [
                '#!/bin/sh',
                '# Auto-generated by AI Contribution Tracker — do not edit manually.',
                '# Sources common profile files so node is found even when VS Code',
                '# launches without the user\'s full shell PATH.',
                '',
                '# nvm',
                'export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"',
                '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" --no-use',
                '',
                '# asdf',
                '[ -f "$HOME/.asdf/asdf.sh" ] && . "$HOME/.asdf/asdf.sh"',
                '',
                '# Homebrew (arm64 / x86)',
                'for _brew_bin in /opt/homebrew/bin /usr/local/bin; do',
                '  [ -x "$_brew_bin/node" ] && export PATH="$_brew_bin:$PATH" && break',
                'done',
                '',
                '# Volta',
                '[ -d "$HOME/.volta/bin" ] && export PATH="$HOME/.volta/bin:$PATH"',
                '',
                'NODE_BIN=""',
                'for _candidate in "$HOME/.volta/bin/node" "$HOME/.asdf/shims/node" /opt/homebrew/bin/node /usr/local/bin/node /usr/bin/node; do',
                '  if [ -x "$_candidate" ]; then',
                '    NODE_BIN="$_candidate"',
                '    break',
                '  fi',
                'done',
                '',
                'if [ -z "$NODE_BIN" ] && [ -d "$NVM_DIR/versions/node" ]; then',
                "  NODE_BIN=$(find \"$NVM_DIR/versions/node\" -path '*/bin/node' -type f 2>/dev/null | sort -r | head -n 1)",
                'fi',
                '',
                'if [ -z "$NODE_BIN" ]; then',
                '  NODE_BIN=$(command -v node 2>/dev/null || true)',
                'fi',
                '',
                'if [ -z "$NODE_BIN" ]; then',
                '  echo "AI Commit Tracker: node not found in Copilot hook environment" >&2',
                '  exit 127',
                'fi',
                '',
                `exec "$NODE_BIN" "${handlerPathPosix}"`,
            ].join('\n') + '\n';

            fs.writeFileSync(wrapperPath, wrapperContent);
            fs.chmodSync(wrapperPath, '755');
            logger.appendLine(`[Setup] Wrote run-hook.sh wrapper: ${wrapperPath}`);

            defaultCommand = `"${wrapperPathPosix}"`;
            windowsCommand = `node "${installedHandler}"`; // unused on non-Windows
        } else {
            defaultCommand = `node "${installedHandler.replace(/\\/g, '/')}"`;
            windowsCommand = `node "${installedHandler}"`;
        }

        const hookConfig = {
            hooks: {
                SessionStart: [{
                    type: 'command',
                    command: defaultCommand,
                    windows: windowsCommand,
                    timeout: 10
                }],
                UserPromptSubmit: [{
                    type: 'command',
                    command: defaultCommand,
                    windows: windowsCommand,
                    timeout: 10
                }],
                SubagentStart: [{
                    type: 'command',
                    command: defaultCommand,
                    windows: windowsCommand,
                    timeout: 10
                }],
                SubagentStop: [{
                    type: 'command',
                    command: defaultCommand,
                    windows: windowsCommand,
                    timeout: 10
                }],
                Stop: [{
                    type: 'command',
                    command: defaultCommand,
                    windows: windowsCommand,
                    timeout: 15
                }]
            }
        };

        const configPath = path.join(copilotHooksDir, 'ai-commit-tracker.json');

        // Guard: only overwrite the hooks config if our installed handler is at least as
        // large as the one already configured. This prevents an older VS Code instance
        // (e.g., stable with a stale extension build) from overwriting a newer one
        // (e.g., Insiders with a freshly compiled build).
        let shouldWriteConfig = true;
        if (fs.existsSync(configPath)) {
            try {
                const existingConfig = JSON.parse(fs.readFileSync(configPath, 'utf8')) as {
                    hooks?: { Stop?: Array<{ windows?: string; command?: string }> };
                };
                const existingCmd = existingConfig?.hooks?.Stop?.[0]?.windows ?? '';
                const existingPathMatch = existingCmd.match(/"([^"]+hook-handler\.js)"/i);
                if (existingPathMatch) {
                    const existingHandlerPath = existingPathMatch[1];
                    if (fs.existsSync(existingHandlerPath)) {
                        const existingSize = fs.statSync(existingHandlerPath).size;
                        const ourSize = fs.statSync(installedHandler).size;
                        if (existingSize > ourSize) {
                            shouldWriteConfig = false;
                            logger.appendLine(
                                `[Setup] Existing handler (${existingSize}b) is newer than ours (${ourSize}b) — keeping existing config at: ${existingHandlerPath}`
                            );
                        }
                    }
                }
            } catch {
                // Unreadable or malformed config — overwrite it
            }
        }

        if (shouldWriteConfig) {
            fs.writeFileSync(configPath, JSON.stringify(hookConfig, null, 2));
            logger.appendLine(`[Setup] ✓ Copilot hooks config written: ${configPath}`);
            logger.appendLine(`[Setup] Tracking events: SessionStart, UserPromptSubmit, SubagentStart, SubagentStop, Stop`);
        }

    } catch (error) {
        logger.appendLine(`[Setup] ERROR setting up Copilot hooks: ${error}`);
    }
}

function ensureAICoAuthorSetting(): void {
    try {
        const gitConfig = vscode.workspace.getConfiguration('git');
        const current = gitConfig.get<string>('addAICoAuthor');
        if (current !== 'all') {
            gitConfig.update('addAICoAuthor', 'all', vscode.ConfigurationTarget.Global);
            logger.appendLine('[Setup] ✓ Set git.addAICoAuthor = "all" globally');
        }
    } catch (error) {
        logger.appendLine(`[Setup] WARNING: Could not set git.addAICoAuthor: ${error}`);
    }
}

/**
 * Ensure the Copilot OTEL DB span exporter is enabled so that token usage data
 * is captured in the local SQLite database at agent-traces.db.
 * This setting takes effect on the next VS Code reload; we notify once if we
 * had to change it.
 */
function ensureOtelDbSpanExporter(): void {
    try {
        const otelConfig = vscode.workspace.getConfiguration('github.copilot.chat.otel');
        const current = otelConfig.get<boolean>('dbSpanExporter.enabled');
        if (!current) {
            otelConfig.update('dbSpanExporter.enabled', true, vscode.ConfigurationTarget.Global);
            logger.appendLine('[Setup] ✓ Enabled github.copilot.chat.otel.dbSpanExporter.enabled (token tracking)');
            vscode.window.showInformationMessage(
                'AI Contribution Tracker: Token usage tracking enabled. Reload VS Code to activate.',
                'Reload Now'
            ).then(selection => {
                if (selection === 'Reload Now') {
                    vscode.commands.executeCommand('workbench.action.reloadWindow');
                }
            });
        } else {
            logger.appendLine('[Setup] OTEL DB span exporter already enabled — token tracking active');
        }
    } catch (error) {
        logger.appendLine(`[Setup] WARNING: Could not set OTEL dbSpanExporter.enabled: ${error}`);
    }
}

/**
 * Remove stale per-repo hook config files left behind by older versions of the extension.
 * Older versions wrote .github/hooks/ai-commit-tracker.json into each workspace folder.
 * Now that hooks are global (~/.copilot/hooks/), per-repo copies cause the handler to
 * fire twice per event, doubling prompt counts and other metrics.
 */
function cleanupLegacyRepoHooks(): void {
    const folders = vscode.workspace.workspaceFolders;
    if (!folders) { return; }

    const legacyPaths = [
        path.join('.github', 'hooks', 'ai-commit-tracker.json'),
        path.join('.copilot', 'hooks', 'ai-commit-tracker.json'),
    ];

    for (const folder of folders) {
        for (const rel of legacyPaths) {
            const full = path.join(folder.uri.fsPath, rel);
            try {
                if (fs.existsSync(full)) {
                    fs.unlinkSync(full);
                    logger.appendLine(`[Setup] Removed legacy per-repo hook config: ${full}`);
                }
            } catch {
                // Non-critical — ignore errors (e.g. read-only filesystem)
            }
        }
    }
}

// Remove installGitHook function since it's moved to tracker
export function deactivate() {
    logger.appendLine('DEACTIVATE: Extension stopping...');
}
