
import * as vscode from 'vscode';
import { CopilotTracker } from './tracker';
import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';
import * as os from 'os';

// Create a global output channel
export const logger = vscode.window.createOutputChannel("AI Tracker Debug");

// Minimal Git API definition
interface GitAPI {
    repositories: Repository[];
}
interface Repository {
    rootUri: vscode.Uri;
}
interface GitExtension {
    getAPI(version: number): GitAPI;
}

export function activate(context: vscode.ExtensionContext) {
    logger.appendLine('ACTIVATE: Extension is starting...');
	console.log('ACTIVATE: Extension is starting (console)...');
    
    // Setup global git hooks
    setupGlobalGitHooks(context);
    
    // Setup Copilot agent hooks
    setupCopilotHooks(context);

    // Setup Claude Code hooks (if Claude Code is installed)
    setupClaudeCodeHooks(context);

    // Setup OpenCode plugin (auto-install to ~/.config/opencode/plugins/)
    setupOpenCodePlugin(context);

    // Register cleanup command
    context.subscriptions.push(
        vscode.commands.registerCommand('aiTracker.removeClaudeCodeHooks', () => removeClaudeCodeHooks())
    );

    // Remove stale per-repo hook configs left by older extension versions
    cleanupLegacyRepoHooks();

    // Ensure Co-authored-by trailer is added for AI contributions
    ensureAICoAuthorSetting();

    // Ensure OTEL DB span exporter is enabled so token usage is captured locally
    ensureOtelDbSpanExporter();
    
    let tracker: CopilotTracker | undefined;

    try {
        tracker = new CopilotTracker(logger);
        context.subscriptions.push(tracker);
        logger.appendLine('ACTIVATE: Tracker initialized.');
    } catch (e) {
        logger.appendLine(`ERROR: Failed to init tracker: ${e}`);
        console.error(e);
    }

	const disposable = vscode.commands.registerCommand('copilot-insight-tracker.helloWorld', () => {
		vscode.window.showInformationMessage('Copilot Insight Tracker is running.');
        logger.appendLine('COMMAND: Hello World triggered');
    });

	context.subscriptions.push(disposable);

    // Write active workspace git dirs so the hook-handler can find the repo
    // even when Copilot CLI / Claude Code fire hooks from a non-repo cwd.
    setupActiveWorkspaceFile(context);
    context.subscriptions.push(
        vscode.workspace.onDidChangeWorkspaceFolders(() => setupActiveWorkspaceFile(context))
    );
    
    return { tracker };
}

/**
 * Setup global git hooks that work across all repositories
 */
function setupGlobalGitHooks(context: vscode.ExtensionContext): void {
    try {
        // Create a global hooks directory in the extension's global storage
        const globalHooksDir = path.join(context.globalStorageUri.fsPath, 'git-hooks');
        
        if (!fs.existsSync(globalHooksDir)) {
            fs.mkdirSync(globalHooksDir, { recursive: true });
            logger.appendLine(`[Setup] Created global hooks directory: ${globalHooksDir}`);
        }

        const hookFile = path.join(globalHooksDir, 'commit-msg');

        // Embed the hook-handler path using forward slashes so Git's POSIX sh
        // can reference it on all platforms (Node.js accepts forward slashes on Windows)
        const hookHandlerPath = path.join(context.globalStorageUri.fsPath, 'copilot-hooks', 'hook-handler.js')
            .replace(/\\/g, '/');

        // The commit-msg hook sources nvm/profile files at runtime so node is found
        // even in Git's restricted hook environment (no baked-in path needed).


        // Create/update the commit-msg hook
        const hookContent = `#!/bin/sh
# Auto-generated by AI Contribution Tracker Extension
# This hook runs globally for all repositories

# Delegate to repo-local commit-msg hook first if one exists
LOCAL_HOOK="$(git rev-parse --path-format=absolute --git-common-dir)/hooks/commit-msg"
if [ -f "$LOCAL_HOOK" ] && [ -x "$LOCAL_HOOK" ]; then
    "$LOCAL_HOOK" "$@" || exit $?
fi

HOOK_HANDLER="${hookHandlerPath}"
IMPACT_FLAG=$(git rev-parse --git-path AI_IMPACT_PENDING)
STATE_FILE=$(git rev-parse --git-path ai-tracker-state.json)

# Source common profile files so node is found even in restricted Git hook envs
export NVM_DIR="\${NVM_DIR:-$HOME/.nvm}"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" --no-use
[ -f "$HOME/.asdf/asdf.sh" ] && . "$HOME/.asdf/asdf.sh"
[ -d "$HOME/.volta/bin" ] && export PATH="$HOME/.volta/bin:$PATH"
for _brew_bin in /opt/homebrew/bin /usr/local/bin; do
  [ -x "$_brew_bin/node" ] && export PATH="$_brew_bin:$PATH" && break
done

NODE_BIN=""
for _candidate in \
    "$HOME/.volta/bin/node" \
    "$HOME/.asdf/shims/node" \
    /opt/homebrew/bin/node \
    /usr/local/bin/node \
    /usr/bin/node; do
    if [ -x "$_candidate" ]; then
        NODE_BIN="$_candidate"
        break
    fi
done

if [ -z "$NODE_BIN" ] && [ -d "$NVM_DIR/versions/node" ]; then
    NODE_BIN=$(find "$NVM_DIR/versions/node" -path '*/bin/node' -type f 2>/dev/null | sort -r | head -n 1)
fi

if [ -z "$NODE_BIN" ]; then
    NODE_BIN=$(command -v node 2>/dev/null || true)
fi

if [ -z "$NODE_BIN" ]; then
    echo "AI Commit Tracker: node not found in commit-msg hook environment" >&2
    exit 127
fi

# Invoke hook-handler to refresh/migrate state and write the flag.
# Always run (not just when STATE_FILE exists locally) because state may have
# been accumulated in a different repo due to cwd fallback, and CommitMsg
# handles migration to the correct repo.
if [ -f "$HOOK_HANDLER" ]; then
    GIT_ABS_DIR=$(git rev-parse --absolute-git-dir)
    printf '{"hookEventName":"CommitMsg","cwd":".","gitDir":"%s"}' "$GIT_ABS_DIR" | "$NODE_BIN" "$HOOK_HANDLER" > /dev/null 2>&1 || true
fi

if [ -f "$IMPACT_FLAG" ]; then
    MARKER=$(cat "$IMPACT_FLAG")
    if [ -z "$MARKER" ]; then
        MARKER="Impacted by AI"
    fi
    if ! grep -qF "$MARKER" "$1"; then
        # Ensure a blank line separator before the marker.
        # If file doesn't end with a newline, add one first.
        if [ -s "$1" ] && [ "$(tail -c 1 "$1" | wc -l)" -eq 0 ]; then
            echo "" >> "$1"
        fi
        echo "" >> "$1"
        echo "$MARKER" >> "$1"
    fi
    rm "$IMPACT_FLAG"
fi

# Clean up accumulated hook state after commit
if [ -f "$STATE_FILE" ]; then
    rm "$STATE_FILE"
fi
`.replace(/\r\n/g, '\n');

        fs.writeFileSync(hookFile, hookContent);
        
        // Make executable on Unix-like systems
        if (os.platform() !== 'win32') {
            fs.chmodSync(hookFile, '755');
        }
        
        logger.appendLine(`[Setup] Created/updated commit-msg hook: ${hookFile}`);

        const passthroughHooks = ['pre-commit', 'pre-push', 'prepare-commit-msg', 'post-commit', 'post-merge', 'pre-rebase'];
        for (const hookName of passthroughHooks) {
            const passthroughFile = path.join(globalHooksDir, hookName);
            if (!fs.existsSync(passthroughFile)) {
                const content = `#!/bin/sh\nLOCAL_HOOK="$(git rev-parse --path-format=absolute --git-common-dir)/hooks/${hookName}"\nif [ -f "$LOCAL_HOOK" ] && [ -x "$LOCAL_HOOK" ]; then\n    "$LOCAL_HOOK" "$@" || exit $?\nfi\n`;
                fs.writeFileSync(passthroughFile, content);
                if (os.platform() !== 'win32') {
                    fs.chmodSync(passthroughFile, '755');
                }
                logger.appendLine(`[Setup] Created passthrough hook: ${hookName}`);
            }
        }

        // Check current git global config
        let currentHooksPath: string = '';
        try {
            currentHooksPath = execSync('git config --global core.hooksPath', { 
                encoding: 'utf8',
                stdio: ['pipe', 'pipe', 'pipe']
            }).trim();
        } catch {
            // Not set, which is fine
        }

        // Set global hooks path if not already set to our directory
        if (currentHooksPath !== globalHooksDir) {
            if (currentHooksPath) {
                logger.appendLine(`[Setup] Existing global hooks path: ${currentHooksPath}`);
                logger.appendLine(`[Setup] Will update to extension hooks path: ${globalHooksDir}`);
            }
            
            execSync(`git config --global core.hooksPath "${globalHooksDir}"`, { 
                encoding: 'utf8',
                stdio: ['pipe', 'pipe', 'pipe']
            });
            
            logger.appendLine(`[Setup] ✓ Set global git hooks path: ${globalHooksDir}`);
            logger.appendLine(`[Setup] All repositories will now use AI tracking hooks automatically`);
            
            // Show notification to user
            vscode.window.showInformationMessage(
                'AI Contribution Tracker: Global git hooks configured successfully. All repositories will now track AI contributions.',
                'Show Logs'
            ).then(selection => {
                if (selection === 'Show Logs') {
                    logger.show();
                }
            });
        } else {
            logger.appendLine(`[Setup] Global hooks path already configured: ${globalHooksDir}`);
        }

    } catch (error) {
        logger.appendLine(`[Setup] ERROR setting up global hooks: ${error}`);
        vscode.window.showWarningMessage(
            `AI Contribution Tracker: Failed to setup global git hooks. Manual installation may be required.`,
            'Show Logs'
        ).then(selection => {
            if (selection === 'Show Logs') {
                logger.show();
            }
        });
    }
}

/**
 * Setup Copilot agent hooks globally (~/.copilot/hooks/)
 * These hooks fire during agent sessions to track prompts, agents, and models.
 */
function setupCopilotHooks(context: vscode.ExtensionContext): void {
    try {
        // Copy hook-handler.js to a stable location in global storage
        const hookHandlerDir = path.join(context.globalStorageUri.fsPath, 'copilot-hooks');
        if (!fs.existsSync(hookHandlerDir)) {
            fs.mkdirSync(hookHandlerDir, { recursive: true });
        }

        const bundledHandler = path.join(context.extensionPath, 'dist', 'hook-handler.js');
        const installedHandler = path.join(hookHandlerDir, 'hook-handler.js');

        if (fs.existsSync(bundledHandler)) {
            fs.copyFileSync(bundledHandler, installedHandler);
            logger.appendLine(`[Setup] Copied hook-handler.js to: ${installedHandler}`);
        } else {
            logger.appendLine(`[Setup] WARNING: hook-handler.js not found at: ${bundledHandler}`);
            return;
        }

        // Create hook config pointing to the installed handler
        const userHome = os.homedir();
        const copilotHooksDir = path.join(userHome, '.copilot', 'hooks');
        if (!fs.existsSync(copilotHooksDir)) {
            fs.mkdirSync(copilotHooksDir, { recursive: true });
        }

        // Build the command string.
        // On Mac/Linux the Copilot hooks subprocess inherits VS Code's restricted
        // environment (not the user's shell), so nvm / Homebrew node may be missing.
        // We create a thin wrapper shell script that sources common profile files
        // before finding and invoking node, rather than baking a path that might
        // be wrong or change after an nvm version switch.
        const handlerPathPosix = installedHandler.replace(/\\/g, '/');
        let defaultCommand: string;
        let windowsCommand: string;

        if (os.platform() !== 'win32') {
            // Create a wrapper script in the same hooks dir
            const wrapperPath = path.join(hookHandlerDir, 'run-hook.sh');
            const wrapperPathPosix = wrapperPath.replace(/\\/g, '/');
            const wrapperContent = [
                '#!/bin/sh',
                '# Auto-generated by AI Contribution Tracker — do not edit manually.',
                '# Sources common profile files so node is found even when VS Code',
                '# launches without the user\'s full shell PATH.',
                '',
                '# nvm',
                'export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"',
                '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" --no-use',
                '',
                '# asdf',
                '[ -f "$HOME/.asdf/asdf.sh" ] && . "$HOME/.asdf/asdf.sh"',
                '',
                '# Homebrew (arm64 / x86)',
                'for _brew_bin in /opt/homebrew/bin /usr/local/bin; do',
                '  [ -x "$_brew_bin/node" ] && export PATH="$_brew_bin:$PATH" && break',
                'done',
                '',
                '# Volta',
                '[ -d "$HOME/.volta/bin" ] && export PATH="$HOME/.volta/bin:$PATH"',
                '',
                'NODE_BIN=""',
                'for _candidate in "$HOME/.volta/bin/node" "$HOME/.asdf/shims/node" /opt/homebrew/bin/node /usr/local/bin/node /usr/bin/node; do',
                '  if [ -x "$_candidate" ]; then',
                '    NODE_BIN="$_candidate"',
                '    break',
                '  fi',
                'done',
                '',
                'if [ -z "$NODE_BIN" ] && [ -d "$NVM_DIR/versions/node" ]; then',
                "  NODE_BIN=$(find \"$NVM_DIR/versions/node\" -path '*/bin/node' -type f 2>/dev/null | sort -r | head -n 1)",
                'fi',
                '',
                'if [ -z "$NODE_BIN" ]; then',
                '  NODE_BIN=$(command -v node 2>/dev/null || true)',
                'fi',
                '',
                'if [ -z "$NODE_BIN" ]; then',
                '  echo "AI Commit Tracker: node not found in Copilot hook environment" >&2',
                '  exit 127',
                'fi',
                '',
                `exec "$NODE_BIN" "${handlerPathPosix}"`,
            ].join('\n') + '\n';

            fs.writeFileSync(wrapperPath, wrapperContent);
            fs.chmodSync(wrapperPath, '755');
            logger.appendLine(`[Setup] Wrote run-hook.sh wrapper: ${wrapperPath}`);

            defaultCommand = `"${wrapperPathPosix}"`;
            windowsCommand = `node "${installedHandler}"`; // unused on non-Windows
        } else {
            defaultCommand = `node "${installedHandler.replace(/\\/g, '/')}"`;
            windowsCommand = `node "${installedHandler}"`;
        }

        const hookConfig = {
            version: 1,
            hooks: {
                SessionStart: [{
                    type: 'command',
                    command: defaultCommand,
                    windows: windowsCommand,
                    timeout: 10
                }],
                UserPromptSubmit: [{
                    type: 'command',
                    command: defaultCommand,
                    windows: windowsCommand,
                    timeout: 10
                }],
                SubagentStart: [{
                    type: 'command',
                    command: defaultCommand,
                    windows: windowsCommand,
                    timeout: 10
                }],
                SubagentStop: [{
                    type: 'command',
                    command: defaultCommand,
                    windows: windowsCommand,
                    timeout: 10
                }],
                Stop: [{
                    type: 'command',
                    command: defaultCommand,
                    windows: windowsCommand,
                    timeout: 15
                }]
            }
        };

        const configPath = path.join(copilotHooksDir, 'ai-commit-tracker.json');

        // Guard: only overwrite the hooks config if our installed handler is at least as
        // large as the one already configured. This prevents an older VS Code instance
        // (e.g., stable with a stale extension build) from overwriting a newer one
        // (e.g., Insiders with a freshly compiled build).
        let shouldWriteConfig = true;
        if (fs.existsSync(configPath)) {
            try {
                const existingConfig = JSON.parse(fs.readFileSync(configPath, 'utf8')) as {
                    hooks?: { Stop?: Array<{ windows?: string; command?: string }> };
                };
                const existingCmd = existingConfig?.hooks?.Stop?.[0]?.windows ?? '';
                const existingPathMatch = existingCmd.match(/"([^"]+hook-handler\.js)"/i);
                if (existingPathMatch) {
                    const existingHandlerPath = existingPathMatch[1];
                    if (fs.existsSync(existingHandlerPath)) {
                        const existingSize = fs.statSync(existingHandlerPath).size;
                        const ourSize = fs.statSync(installedHandler).size;
                        if (existingSize > ourSize) {
                            shouldWriteConfig = false;
                            logger.appendLine(
                                `[Setup] Existing handler (${existingSize}b) is newer than ours (${ourSize}b) — keeping existing config at: ${existingHandlerPath}`
                            );
                        }
                    }
                }
            } catch {
                // Unreadable or malformed config — overwrite it
            }
        }

        if (shouldWriteConfig) {
            fs.writeFileSync(configPath, JSON.stringify(hookConfig, null, 2));
            logger.appendLine(`[Setup] ✓ Copilot hooks config written: ${configPath}`);
            logger.appendLine(`[Setup] Tracking events: SessionStart, UserPromptSubmit, SubagentStart, SubagentStop, Stop`);
        }

    } catch (error) {
        logger.appendLine(`[Setup] ERROR setting up Copilot hooks: ${error}`);
    }
}

/**
 * Setup Claude Code hooks in ~/.claude/settings.json
 * Claude Code uses a nested hook format: hooks.EventName -> [{ hooks: [{ type, command }] }]
 */
function setupClaudeCodeHooks(context: vscode.ExtensionContext): void {
    try {
        const config = vscode.workspace.getConfiguration('aiTracker');
        if (!config.get<boolean>('enableClaudeCodeHooks', true)) {
            logger.appendLine('[Setup] Claude Code hooks disabled by configuration');
            return;
        }

        const userHome = os.homedir();
        const claudeDir = path.join(userHome, '.claude');

        // Skip if Claude Code is not installed
        if (!fs.existsSync(claudeDir)) {
            logger.appendLine('[Setup] ~/.claude/ not found — skipping Claude Code hooks setup');
            return;
        }

        // Ensure hook-handler.js is already installed (setupCopilotHooks does this)
        const hookHandlerDir = path.join(context.globalStorageUri.fsPath, 'copilot-hooks');
        const installedHandler = path.join(hookHandlerDir, 'hook-handler.js');
        if (!fs.existsSync(installedHandler)) {
            logger.appendLine('[Setup] hook-handler.js not yet installed — skipping Claude Code hooks');
            return;
        }

        const settingsPath = path.join(claudeDir, 'settings.json');
        let settings: Record<string, unknown> = {};

        // Read existing settings
        if (fs.existsSync(settingsPath)) {
            try {
                const raw = fs.readFileSync(settingsPath, 'utf8');
                settings = JSON.parse(raw) as Record<string, unknown>;
            } catch (e) {
                logger.appendLine(`[Setup] WARNING: Could not parse ~/.claude/settings.json: ${e}`);
                // Create backup of corrupted file
                const backupPath = settingsPath + '.bak';
                fs.copyFileSync(settingsPath, backupPath);
                logger.appendLine(`[Setup] Backed up corrupted settings to: ${backupPath}`);
                settings = {};
            }
        }

        // Build command string
        const handlerPathPosix = installedHandler.replace(/\\/g, '/');
        const command = `node "${handlerPathPosix}"`;

        // Events we track
        const trackedEvents = ['SessionStart', 'UserPromptSubmit', 'SubagentStart', 'SubagentStop', 'Stop'];

        // Get or create hooks object
        let hooks = settings.hooks as Record<string, unknown[]> | undefined;
        if (!hooks || typeof hooks !== 'object') {
            hooks = {};
        }

        let modified = false;

        for (const eventName of trackedEvents) {
            const eventHooks = hooks[eventName] as Array<{ hooks?: Array<{ type?: string; command?: string; timeout?: number; [key: string]: unknown }> }> | undefined;

            if (!eventHooks || !Array.isArray(eventHooks)) {
                // No hooks for this event — add ours
                hooks[eventName] = [{
                    hooks: [{
                        type: 'command',
                        command: command,
                        timeout: eventName === 'Stop' ? 15 : 10
                    }]
                }];
                modified = true;
                continue;
            }

            // Check if our handler is already registered
            let found = false;
            for (const matcherGroup of eventHooks) {
                if (!matcherGroup.hooks || !Array.isArray(matcherGroup.hooks)) { continue; }
                for (let i = 0; i < matcherGroup.hooks.length; i++) {
                    const handler = matcherGroup.hooks[i];
                    if (handler.command && handler.command.includes('hook-handler.js')) {
                        // Update command path in case handler was reinstalled
                        if (handler.command !== command) {
                            matcherGroup.hooks[i] = {
                                ...handler,
                                command: command
                            };
                            modified = true;
                        }
                        found = true;
                        break;
                    }
                }
                if (found) { break; }
            }

            if (!found) {
                // Append our matcher group
                eventHooks.push({
                    hooks: [{
                        type: 'command',
                        command: command,
                        timeout: eventName === 'Stop' ? 15 : 10
                    }]
                });
                modified = true;
            }
        }

        if (modified) {
            // Backup existing settings on first modification
            const backupPath = settingsPath + '.bak';
            if (fs.existsSync(settingsPath) && !fs.existsSync(backupPath)) {
                fs.copyFileSync(settingsPath, backupPath);
                logger.appendLine(`[Setup] Backed up ~/.claude/settings.json to: ${backupPath}`);
            }

            settings.hooks = hooks;
            fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
            logger.appendLine('[Setup] \u2713 Claude Code hooks written to ~/.claude/settings.json');
            logger.appendLine(`[Setup] Tracking events: ${trackedEvents.join(', ')}`);
        } else {
            logger.appendLine('[Setup] Claude Code hooks already configured — no changes needed');
        }

    } catch (error) {
        logger.appendLine(`[Setup] ERROR setting up Claude Code hooks: ${error}`);
    }
}

/**
 * Register the OpenCode plugin via npm in ~/.config/opencode/opencode.json.
 * OpenCode automatically installs npm plugins via Bun at startup.
 *
 * On Windows, OpenCode typically runs inside WSL so we also write the config
 * into the default WSL distro's ~/.config/opencode/ when WSL is available.
 */
function setupOpenCodePlugin(_context: vscode.ExtensionContext): void {
    const pluginName = '@rachel_rotenberg/ai-contribution-tracker';

    // Always configure the native OS path (works for Linux, macOS, and native Windows)
    const nativeConfigDir = path.join(os.homedir(), '.config', 'opencode');
    addOpenCodePluginToConfig(nativeConfigDir, pluginName);

    // On Windows, also configure in the default WSL distro
    if (process.platform === 'win32') {
        try {
            const wslHome = execSync('wsl -e sh -c "echo $HOME"', { encoding: 'utf8', timeout: 5000 }).trim();
            if (wslHome) {
                const wslConfigDir = execSync(
                    `wsl -e wslpath -w "${wslHome}/.config/opencode"`,
                    { encoding: 'utf8', timeout: 5000 }
                ).trim();
                if (wslConfigDir) {
                    addOpenCodePluginToConfig(wslConfigDir, pluginName);
                }
            }
        } catch {
            logger.appendLine('[Setup] WSL not available — skipping WSL OpenCode config');
        }
    }
}

/** Add the plugin to the "plugin" array in opencode.json if not already present. */
function addOpenCodePluginToConfig(configDir: string, pluginName: string): void {
    try {
        fs.mkdirSync(configDir, { recursive: true });
        const configPath = path.join(configDir, 'opencode.json');

        let config: Record<string, unknown> = {};
        if (fs.existsSync(configPath)) {
            try {
                config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
            } catch {
                fs.copyFileSync(configPath, configPath + '.bak');
                config = {};
            }
        }

        let plugins = config.plugin as Array<string | [string, Record<string, unknown>]> | undefined;
        if (!Array.isArray(plugins)) {
            plugins = [];
        }

        // Check if already registered (plain string or tuple form)
        const alreadyRegistered = plugins.some(
            p => (typeof p === 'string' ? p : p[0]) === pluginName
        );
        if (alreadyRegistered) {
            logger.appendLine(`[Setup] OpenCode plugin already configured: ${configPath}`);
            return;
        }

        plugins.push(pluginName);
        config.plugin = plugins;
        fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
        logger.appendLine(`[Setup] ✓ Added OpenCode plugin to: ${configPath}`);
    } catch (error) {
        logger.appendLine(`[Setup] ERROR configuring OpenCode plugin at ${configDir}: ${error}`);
    }
}

/**
 * Remove AI Tracker hooks from ~/.claude/settings.json
 */
function removeClaudeCodeHooks(): void {
    try {
        const userHome = os.homedir();
        const settingsPath = path.join(userHome, '.claude', 'settings.json');

        if (!fs.existsSync(settingsPath)) {
            vscode.window.showInformationMessage('No Claude Code settings found — nothing to remove.');
            return;
        }

        const raw = fs.readFileSync(settingsPath, 'utf8');
        const settings = JSON.parse(raw) as Record<string, unknown>;
        const hooks = settings.hooks as Record<string, unknown[]> | undefined;

        if (!hooks || typeof hooks !== 'object') {
            vscode.window.showInformationMessage('No hooks found in Claude Code settings.');
            return;
        }

        let removed = false;
        const trackedEvents = ['SessionStart', 'UserPromptSubmit', 'SubagentStart', 'SubagentStop', 'Stop'];

        for (const eventName of trackedEvents) {
            const eventHooks = hooks[eventName] as Array<{ hooks?: Array<{ command?: string }> }> | undefined;
            if (!eventHooks || !Array.isArray(eventHooks)) { continue; }

            // Filter out matcher groups that only contain our handler
            const filtered = eventHooks.filter(matcherGroup => {
                if (!matcherGroup.hooks || !Array.isArray(matcherGroup.hooks)) { return true; }
                // Remove our handlers from this group
                const remaining = matcherGroup.hooks.filter(
                    h => !h.command || !h.command.includes('hook-handler.js')
                );
                if (remaining.length === 0) {
                    // Entire matcher group was only ours — remove it
                    removed = true;
                    return false;
                }
                if (remaining.length < matcherGroup.hooks.length) {
                    matcherGroup.hooks = remaining;
                    removed = true;
                }
                return true;
            });

            if (filtered.length === 0) {
                delete hooks[eventName];
            } else {
                hooks[eventName] = filtered;
            }
        }

        if (removed) {
            // Remove hooks key entirely if empty
            if (Object.keys(hooks).length === 0) {
                delete settings.hooks;
            } else {
                settings.hooks = hooks;
            }
            fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
            vscode.window.showInformationMessage('AI Tracker hooks removed from Claude Code settings.');
            logger.appendLine('[Cleanup] Removed AI Tracker hooks from ~/.claude/settings.json');
        } else {
            vscode.window.showInformationMessage('No AI Tracker hooks found in Claude Code settings.');
        }

    } catch (error) {
        logger.appendLine(`[Cleanup] ERROR removing Claude Code hooks: ${error}`);
        vscode.window.showErrorMessage(`Failed to remove Claude Code hooks: ${error}`);
    }
}

function ensureAICoAuthorSetting(): void {
    try {
        const gitConfig = vscode.workspace.getConfiguration('git');
        const current = gitConfig.get<string>('addAICoAuthor');
        if (current !== 'all') {
            gitConfig.update('addAICoAuthor', 'all', vscode.ConfigurationTarget.Global);
            logger.appendLine('[Setup] ✓ Set git.addAICoAuthor = "all" globally');
        }
    } catch (error) {
        logger.appendLine(`[Setup] WARNING: Could not set git.addAICoAuthor: ${error}`);
    }
}

/**
 * Ensure the Copilot OTEL DB span exporter is enabled so that token usage data
 * is captured in the local SQLite database at agent-traces.db.
 * This setting takes effect on the next VS Code reload; we notify once if we
 * had to change it.
 */
function ensureOtelDbSpanExporter(): void {
    try {
        const otelConfig = vscode.workspace.getConfiguration('github.copilot.chat.otel');
        const current = otelConfig.get<boolean>('dbSpanExporter.enabled');
        if (!current) {
            otelConfig.update('dbSpanExporter.enabled', true, vscode.ConfigurationTarget.Global);
            logger.appendLine('[Setup] ✓ Enabled github.copilot.chat.otel.dbSpanExporter.enabled (token tracking)');
            vscode.window.showInformationMessage(
                'AI Contribution Tracker: Token usage tracking enabled. Reload VS Code to activate.',
                'Reload Now'
            ).then(selection => {
                if (selection === 'Reload Now') {
                    vscode.commands.executeCommand('workbench.action.reloadWindow');
                }
            });
        } else {
            logger.appendLine('[Setup] OTEL DB span exporter already enabled — token tracking active');
        }
    } catch (error) {
        logger.appendLine(`[Setup] WARNING: Could not set OTEL dbSpanExporter.enabled: ${error}`);
    }
}

/**
/**
 * Remove stale per-repo hook config files left behind by older versions of the extension.
 * Older versions wrote .github/hooks/ai-commit-tracker.json into each workspace folder.
 * Now that hooks are global (~/.copilot/hooks/), per-repo copies cause the handler to
 * fire twice per event, doubling prompt counts and other metrics.
 */
function cleanupLegacyRepoHooks(): void {
    const folders = vscode.workspace.workspaceFolders;
    if (!folders) { return; }

    const legacyPaths = [
        path.join('.github', 'hooks', 'ai-commit-tracker.json'),
        path.join('.copilot', 'hooks', 'ai-commit-tracker.json'),
    ];

    for (const folder of folders) {
        for (const rel of legacyPaths) {
            const full = path.join(folder.uri.fsPath, rel);
            try {
                if (fs.existsSync(full)) {
                    fs.unlinkSync(full);
                    logger.appendLine(`[Setup] Removed legacy per-repo hook config: ${full}`);
                }
            } catch {
                // Non-critical — ignore errors (e.g. read-only filesystem)
            }
        }
    }
}

/**
 * Write the git dirs of all open workspace folders to a well-known file in
 * globalStorage so that the hook-handler can locate the correct repo even
 * when Copilot CLI / Claude Code fire hooks from a non-repo cwd (e.g. C:\WINDOWS\system32).
 */
function setupActiveWorkspaceFile(context: vscode.ExtensionContext): void {
    try {
        const folders = vscode.workspace.workspaceFolders;
        if (!folders || folders.length === 0) { return; }

        const gitDirs: string[] = [];
        for (const folder of folders) {
            const dotGit = path.join(folder.uri.fsPath, '.git');
            if (fs.existsSync(dotGit)) {
                gitDirs.push(folder.uri.fsPath);
            }
        }
        if (gitDirs.length === 0) { return; }

        const outPath = path.join(context.globalStorageUri.fsPath, 'active-workspace.json');
        fs.mkdirSync(path.dirname(outPath), { recursive: true });

        // Merge with existing workspaces (other VS Code windows may have written theirs)
        let existing: string[] = [];
        if (fs.existsSync(outPath)) {
            try {
                const data = JSON.parse(fs.readFileSync(outPath, 'utf8'));
                existing = Array.isArray(data.workspaces) ? data.workspaces : [];
            } catch { /* corrupt file, overwrite */ }
        }
        const merged = [...new Set([...existing, ...gitDirs])];
        fs.writeFileSync(outPath, JSON.stringify({ workspaces: merged }));
    } catch (e) {
        logger.appendLine(`[setupActiveWorkspaceFile] error: ${e}`);
    }
}

export function deactivate() {
    logger.appendLine('DEACTIVATE: Extension stopping...');
}
