// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';
import { CopilotTracker } from './tracker';
import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';
import * as os from 'os';

// Create a global output channel
export const logger = vscode.window.createOutputChannel("AI Tracker Debug");

// Minimal Git API definition
interface GitAPI {
    repositories: Repository[];
}
interface Repository {
    rootUri: vscode.Uri;
}
interface GitExtension {
    getAPI(version: number): GitAPI;
}

export function activate(context: vscode.ExtensionContext) {
    logger.appendLine('ACTIVATE: Extension is starting...');
	console.log('ACTIVATE: Extension is starting (console)...');
    
    // Setup global git hooks
    setupGlobalGitHooks(context);
    
    let tracker: CopilotTracker | undefined;

    try {
        tracker = new CopilotTracker(logger);
        context.subscriptions.push(tracker);
        logger.appendLine('ACTIVATE: Tracker initialized.');
    } catch (e) {
        logger.appendLine(`ERROR: Failed to init tracker: ${e}`);
        console.error(e);
    }

	const disposable = vscode.commands.registerCommand('copilot-insight-tracker.helloWorld', () => {
		vscode.window.showInformationMessage('Copilot Insight Tracker is running.');
        logger.appendLine('COMMAND: Hello World triggered');
    });

	context.subscriptions.push(disposable);
    
    // Log configuration
    const config = vscode.workspace.getConfiguration('copilotInsightTracker');
    logger.appendLine(`CONFIG: agenticConfidenceThreshold=${config.get('agenticConfidenceThreshold')}`);
    
    return { tracker };
}

/**
 * Setup global git hooks that work across all repositories
 */
function setupGlobalGitHooks(context: vscode.ExtensionContext): void {
    try {
        // Create a global hooks directory in the extension's global storage
        const globalHooksDir = path.join(context.globalStorageUri.fsPath, 'git-hooks');
        
        if (!fs.existsSync(globalHooksDir)) {
            fs.mkdirSync(globalHooksDir, { recursive: true });
            logger.appendLine(`[Setup] Created global hooks directory: ${globalHooksDir}`);
        }

        const hookFile = path.join(globalHooksDir, 'commit-msg');

        // Create/update the commit-msg hook
        const hookContent = `#!/bin/sh
# Auto-generated by AI Contribution Tracker Extension
# This hook runs globally for all repositories

IMPACT_FLAG=$(git rev-parse --git-path AI_IMPACT_PENDING)

if [ -f "$IMPACT_FLAG" ]; then
    MARKER=$(cat "$IMPACT_FLAG")
    if [ -z "$MARKER" ]; then
        MARKER="Impacted by AI"
    fi
    if ! grep -q "$MARKER" "$1"; then
        echo "" >> "$1"
        echo "$MARKER" >> "$1"
    fi
    rm "$IMPACT_FLAG"
fi
`.replace(/\r\n/g, '\n');

        fs.writeFileSync(hookFile, hookContent);
        
        // Make executable on Unix-like systems
        if (os.platform() !== 'win32') {
            fs.chmodSync(hookFile, '755');
        }
        
        logger.appendLine(`[Setup] Created/updated commit-msg hook: ${hookFile}`);

        // Check current git global config
        let currentHooksPath: string = '';
        try {
            currentHooksPath = execSync('git config --global core.hooksPath', { 
                encoding: 'utf8',
                stdio: ['pipe', 'pipe', 'pipe']
            }).trim();
        } catch {
            // Not set, which is fine
        }

        // Set global hooks path if not already set to our directory
        if (currentHooksPath !== globalHooksDir) {
            if (currentHooksPath) {
                logger.appendLine(`[Setup] Existing global hooks path: ${currentHooksPath}`);
                logger.appendLine(`[Setup] Will update to extension hooks path: ${globalHooksDir}`);
            }
            
            execSync(`git config --global core.hooksPath "${globalHooksDir}"`, { 
                encoding: 'utf8',
                stdio: ['pipe', 'pipe', 'pipe']
            });
            
            logger.appendLine(`[Setup] ✓ Set global git hooks path: ${globalHooksDir}`);
            logger.appendLine(`[Setup] All repositories will now use AI tracking hooks automatically`);
            
            // Show notification to user
            vscode.window.showInformationMessage(
                'AI Contribution Tracker: Global git hooks configured successfully. All repositories will now track AI contributions.',
                'Show Logs'
            ).then(selection => {
                if (selection === 'Show Logs') {
                    logger.show();
                }
            });
        } else {
            logger.appendLine(`[Setup] Global hooks path already configured: ${globalHooksDir}`);
        }

    } catch (error) {
        logger.appendLine(`[Setup] ERROR setting up global hooks: ${error}`);
        vscode.window.showWarningMessage(
            `AI Contribution Tracker: Failed to setup global git hooks. Manual installation may be required.`,
            'Show Logs'
        ).then(selection => {
            if (selection === 'Show Logs') {
                logger.show();
            }
        });
    }
}

// Remove installGitHook function since it's moved to tracker
export function deactivate() {
    logger.appendLine('DEACTIVATE: Extension stopping...');
}
